<?php

namespace Ephp\WsBundle\Entity\Log;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogResponseRepository extends EntityRepository
{
}