<?php

namespace Ephp\WsBundle\Entity\Log;

use Doctrine\ORM\EntityRepository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRequestRepository extends EntityRepository
{
}